package interfaces;


/**
* interfaces/UsersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserApp.idl
* piątek, 25 listopada 2016 08:35:57 CET
*/

public final class UsersHolder implements org.omg.CORBA.portable.Streamable
{
  public interfaces.User value[] = null;

  public UsersHolder ()
  {
  }

  public UsersHolder (interfaces.User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = interfaces.UsersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    interfaces.UsersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return interfaces.UsersHelper.type ();
  }

}
