package interfaces;


/**
* interfaces/UserServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserApp.idl
* piątek, 25 listopada 2016 08:35:57 CET
*/

public interface UserServiceOperations 
{
  interfaces.User createUser (interfaces.User user);
  String deleteUser (int userId);
  interfaces.User getUser ();
  interfaces.User updateUser (interfaces.User user);
  interfaces.User[] getUsers ();
} // interface UserServiceOperations
