package interfaces;


/**
* interfaces/UserService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserApp.idl
* piątek, 25 listopada 2016 08:30:40 CET
*/

public interface UserService extends UserServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserService
