package interfaces;


/**
* interfaces/UserServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserApp.idl
* piątek, 25 listopada 2016 01:22:17 CET
*/

public interface UserServiceOperations 
{
  void createUser (interfaces.User user);
  void deleteUser (interfaces.User user);
  void getUser (interfaces.User user);
  void updateUser (interfaces.User user);
} // interface UserServiceOperations
