package interfaces;

/**
* interfaces/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserApp.idl
* piątek, 25 listopada 2016 08:40:29 CET
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public interfaces.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (interfaces.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = interfaces.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    interfaces.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return interfaces.UserHelper.type ();
  }

}
