package interfaces;


/**
* interfaces/UserServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserApp.idl
* piątek, 25 listopada 2016 08:40:29 CET
*/

abstract public class UserServiceHelper
{
  private static String  _id = "IDL:interfaces/UserService:1.0";

  public static void insert (org.omg.CORBA.Any a, interfaces.UserService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static interfaces.UserService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (UserServiceHelper.id (), "UserService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static interfaces.UserService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_UserServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, interfaces.UserService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static interfaces.UserService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interfaces.UserService)
      return (interfaces.UserService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      interfaces._UserServiceStub stub = new interfaces._UserServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static interfaces.UserService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interfaces.UserService)
      return (interfaces.UserService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      interfaces._UserServiceStub stub = new interfaces._UserServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
