package interfaces;


/**
* interfaces/UsersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserApp.idl
* piątek, 25 listopada 2016 08:40:29 CET
*/

public final class UsersHolder implements org.omg.CORBA.portable.Streamable
{
  public User value[] = null;

  public UsersHolder ()
  {
  }

  public UsersHolder (User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UsersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UsersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UsersHelper.type ();
  }

}
