module interfaces {
    struct User {
    		string login;
    		string name;
    		string surname;
    		long age;
    		boolean isAdmin;
    };

    typedef sequence<User> Users;

    interface UserService {
    		User createUser(in User user);
    		string deleteUser(in User user);
    		User getUser();
    		User updateUser(in User user);
    		Users getUsers();
    };
};